services:
  postgres:
    image: postgres:16
    container_name: gabinete-digital-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: gabinete
      POSTGRES_PASSWORD: gabinete123
      POSTGRES_DB: gabinete_digital
    ports:
      - "15432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: gabinete-digital-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gabinete.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
